#!/usr/bin/env node
/**
 * Emits the pre-auction squads as re-runnable SQL.
 *
 * The retained forty are fixed for the season, so this is written to be applied
 * on every load. Unlike the auction insert it UPSERTS: re-running restores
 * status, sold_to and pre_auction_role even if a later load left a player
 * looking Available. That is the failure this replaces — 24 retained players
 * sat in the auction pool with sold_to NULL, biddable by any team.
 *
 * Teams are upserted first because players.sold_to is a foreign key onto
 * teams.team_name.
 *
 *   node scripts/export_preauction_sql.js
 */
const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const WORKBOOK = path.join('data', 'CPL_2026_PreAuction_Template.xlsx');
const SQL_OUT = path.join('sql', '2026_pre_auction_insert.sql');
const BUDGET = 1000;
const SQUAD_SIZE = 15;

const q = v => (v === null || v === undefined || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

const wb = XLSX.readFile(WORKBOOK);
const teams = XLSX.utils.sheet_to_json(wb.Sheets.Teams, { defval: '' });
const players = XLSX.utils.sheet_to_json(wb.Sheets.PreAuction, { defval: '' });

const problems = [];
players.forEach(p => {
  if (!p.PlayerID) problems.push(`${p.Name || '(no name)'} (${p.TeamName}): missing PlayerID`);
  if (!p.Role) problems.push(`${p.Name} (${p.TeamName}): missing Role`);
  if (!['Captain', 'ViceCaptain', 'Squad'].includes(p.PreAuctionRole)) {
    problems.push(`${p.Name}: bad PreAuctionRole "${p.PreAuctionRole}"`);
  }
});
const teamNames = new Set(teams.map(t => t.TeamName));
players.forEach(p => { if (!teamNames.has(p.TeamName)) problems.push(`${p.Name}: unknown team "${p.TeamName}"`); });

if (problems.length) {
  console.error('Cannot export:');
  problems.forEach(p => console.error(`  - ${p}`));
  process.exit(1);
}

const teamValues = teams.map(t => `  (${[
  q(t.TeamID), q(t.TeamName), q(t.LogoFile || null), BUDGET, BUDGET, SQUAD_SIZE
].join(', ')})`).join(',\n');

const playerValues = players.map(p => `  (${[
  q(p.PlayerID), q(p.Name), q(p.Role), Number(p.BaseTokens) || 0,
  q(p.PhotoFileName || null), q(p.Department || null),
  q(p.PreAuctionRole), q(p.TeamName),
  p.PreAuctionRole === 'Captain', p.PreAuctionRole === 'ViceCaptain',
  q(p.Availability || 'Unknown'),
  "'PreAuction'", 0
].join(', ')})`).join(',\n');

fs.writeFileSync(SQL_OUT, `-- CPL 2026 pre-auction squads: ${teams.length} teams, ${players.length} players.
-- Generated by scripts/export_preauction_sql.js from ${WORKBOOK}.
--
-- Re-runnable by design. The retained squads are fixed for the season, so this
-- UPSERTS: running it again restores status, sold_to and pre_auction_role for
-- any player a later load knocked back to Available.
--
-- Run this BEFORE the auction pool insert.

INSERT INTO teams (team_id, team_name, logo_file, tokens_left, max_tokens, max_squad_size) VALUES
${teamValues}
ON CONFLICT (team_id) DO UPDATE SET
  team_name = EXCLUDED.team_name,
  logo_file = EXCLUDED.logo_file;

INSERT INTO players (
  player_id, name, role, base_tokens, photo_filename, department,
  pre_auction_role, sold_to, is_captain, is_vice_captain, availability,
  status, sold_price
) VALUES
${playerValues}
ON CONFLICT (player_id) DO UPDATE SET
  name             = EXCLUDED.name,
  role             = EXCLUDED.role,
  photo_filename   = EXCLUDED.photo_filename,
  pre_auction_role = EXCLUDED.pre_auction_role,
  sold_to          = EXCLUDED.sold_to,
  is_captain       = EXCLUDED.is_captain,
  is_vice_captain  = EXCLUDED.is_vice_captain,
  status           = 'PreAuction',
  sold_price       = 0;
`, 'utf8');

const perTeam = players.reduce((a, p) => ({ ...a, [p.TeamName]: (a[p.TeamName] || 0) + 1 }), {});
console.log(`Wrote ${SQL_OUT}`);
console.log(`  ${teams.length} teams, ${players.length} players`);
console.log(`  squad sizes: ${Object.entries(perTeam).map(([t, n]) => `${t} ${n}`).join(', ')}`);
