#!/usr/bin/env node
/**
 * Builds the auction-pool upload from CPL2026.xlsx "Auction Players".
 *
 * The sheet has 65 rows, six of which are entirely blank, leaving 59 real
 * registrations. Blank rows are dropped rather than exported as empty players.
 *
 * Emits two interchangeable artefacts:
 *   data/CPL_2026_AuctionPlayers.xlsx   for the admin Excel upload
 *   sql/2026_auction_players_insert.sql for running directly against Supabase
 *
 * Load ONE of them, not both. The SQL is idempotent (ON CONFLICT DO NOTHING),
 * the Excel path is not.
 *
 *   node scripts/export_auction_players_from_cpl2026.js
 */
const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const SOURCE = 'CPL2026.xlsx';
const PHOTO_DIR = path.join('public', 'players');
const XLSX_OUT = path.join('data', 'CPL_2026_AuctionPlayers.xlsx');
const SQL_OUT = path.join('sql', '2026_auction_players_insert.sql');

/**
 * Registration wording -> the four roles the players.role CHECK constraint
 * allows. Both all-rounder variants collapse to All-rounder.
 */
const ROLE_MAP = {
  'batsman': 'Batsman',
  'bowler': 'Bowler',
  'batting all-rounder': 'All-rounder',
  'bowling all-rounder': 'All-rounder',
  'all-rounder': 'All-rounder',
  'wicket keeper': 'WicketKeeper',
  'wicketkeeper': 'WicketKeeper'
};

/**
 * Opening price by role, mirroring the lowest 2025 values. All-rounders start
 * higher because they carry the highest bid ceiling (350 vs 250/150).
 * Change here to reprice the whole pool.
 */
const BASE_TOKENS = { Batsman: 35, Bowler: 35, 'All-rounder': 40, WicketKeeper: 35 };

const TEAMS = [
  { TeamID: 'CPL_T01', TeamName: 'Avengers',         LogoFile: 'Avengers.png' },
  { TeamID: 'CPL_T02', TeamName: 'Fearless Falcons', LogoFile: 'Feralessfalcons.png' },
  { TeamID: 'CPL_T03', TeamName: 'Hits & Misses',    LogoFile: 'HitsMisses.png' },
  { TeamID: 'CPL_T04', TeamName: 'Mavericks',        LogoFile: 'Mavericks.png' },
  { TeamID: 'CPL_T05', TeamName: 'Quality Strikers', LogoFile: 'quality_strikers.png' },
  { TeamID: 'CPL_T06', TeamName: 'Pirates',          LogoFile: 'Pirates.png' },
  { TeamID: 'CPL_T07', TeamName: 'CSK',              LogoFile: 'csk.png' },
  { TeamID: 'CPL_T08', TeamName: 'Digititans',       LogoFile: 'digititans.png' }
];

const photos = new Map(fs.readdirSync(PHOTO_DIR).map(f => [f.toLowerCase(), f]));
const sqlString = value => (value === null || value === '' ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`);

const rows = XLSX.utils
  .sheet_to_json(XLSX.readFile(SOURCE).Sheets['Auction Players'], { defval: '' })
  .filter(r => String(r['Full Name']).trim() !== '');

const problems = [];
const players = rows.map((r, i) => {
  const name = String(r['Full Name']).trim();
  const playerId = String(r['Employee ID']).trim();
  const preferred = String(r['Preferred Role']).trim().toLowerCase();
  const role = ROLE_MAP[preferred];

  if (!playerId) problems.push(`${name}: no Employee ID`);
  if (!role) problems.push(`${name}: unmapped Preferred Role "${r['Preferred Role']}"`);

  const photo = photos.get(`${playerId.toLowerCase()}.jpg`) || '';
  return {
    PlayerID: playerId,
    Name: name,
    Role: role || '',
    BaseTokens: role ? BASE_TOKENS[role] : '',
    PhotoFileName: photo,
    Department: '',
    Status: 'Available',
    AuctionOrder: i + 1
  };
});

const duplicates = players
  .map(p => p.PlayerID)
  .filter((id, i, all) => id && all.indexOf(id) !== i);
if (duplicates.length) problems.push(`duplicate Employee IDs: ${[...new Set(duplicates)].join(', ')}`);

if (problems.length) {
  console.error('Cannot export:');
  problems.forEach(p => console.error(`  - ${p}`));
  process.exit(1);
}

const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(players), 'Players');
XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(TEAMS), 'Teams');
XLSX.writeFile(wb, XLSX_OUT);

const values = players.map(p => `  (${[
  sqlString(p.PlayerID), sqlString(p.Name), sqlString(p.Role), p.BaseTokens,
  sqlString(p.PhotoFileName || null), 'NULL', p.AuctionOrder, `'Available'`, 'NULL', '0', 'false', 'false'
].join(', ')})`).join(',\n');

fs.writeFileSync(SQL_OUT, `-- CPL 2026 auction pool: ${players.length} players.
-- Generated by scripts/export_auction_players_from_cpl2026.js from ${SOURCE}.
-- Do NOT also run the Excel upload for these players; pick one route.
-- Safe to re-run: existing player_id rows are left untouched.

INSERT INTO players (
  player_id, name, role, base_tokens, photo_filename, department,
  auction_order, status, sold_to, sold_price, is_captain, is_vice_captain
) VALUES
${values}
ON CONFLICT (player_id) DO NOTHING;
`, 'utf8');

const byRole = players.reduce((acc, p) => ({ ...acc, [p.Role]: (acc[p.Role] || 0) + 1 }), {});
console.log(`Wrote ${XLSX_OUT} and ${SQL_OUT}`);
console.log(`  ${players.length} players: ${Object.entries(byRole).map(([r, n]) => `${r} ${n}`).join(', ')}`);
console.log(`  ${players.filter(p => p.PhotoFileName).length} with photos, ${players.filter(p => !p.PhotoFileName).length} without`);
