-- CPL 2026 auction log verification (READ ONLY -- no writes, no COMMIT).
-- Generated by scripts/export_squads_config.js from data\auction_log_2026.csv.
-- Compares the live database against data/auction_log_2026.csv. Nothing changes
-- until you run sql/2026_apply_auction_log.sql.

WITH log (player_id, team_name, sold_price) AS (
  VALUES
    ('7MW4', 'Avengers', 65),
    ('8HD9', 'Avengers', 205),
    ('8e5y', 'Avengers', 45),
    ('3WRK', 'Avengers', 35),
    ('5RH4', 'Avengers', 35),
    ('7J9A', 'Avengers', 350),
    ('4KQQ', 'Avengers', 190),
    ('CNC8', 'Avengers', 55),
    ('JJH6', 'Fearless Falcons', 45),
    ('3WN4', 'Fearless Falcons', 65),
    ('5L1C', 'Fearless Falcons', 55),
    ('248V', 'Fearless Falcons', 125),
    ('4x97', 'Fearless Falcons', 320),
    ('4WTI', 'Fearless Falcons', 170),
    ('8KA4', 'Fearless Falcons', 40),
    ('5DVA', 'Fearless Falcons', 100),
    ('9TXV', 'Fearless Falcons', 80),
    ('8LQL', 'Hits & Misses', 35),
    ('6JPT', 'Hits & Misses', 35),
    ('836I', 'Hits & Misses', 55),
    ('JPL9', 'Hits & Misses', 35),
    ('8J9Q', 'Hits & Misses', 260),
    ('QTC9', 'Hits & Misses', 350),
    ('81KV', 'Hits & Misses', 60),
    ('5E6D', 'Hits & Misses', 80),
    ('JKJ8', 'Hits & Misses', 85),
    ('84MR', 'Mavericks', 45),
    ('131X', 'Mavericks', 65),
    ('7ttv', 'Mavericks', 35),
    ('54RP', 'Mavericks', 295),
    ('PVH5', 'Mavericks', 70),
    ('4TDM', 'Mavericks', 210),
    ('QDK7', 'Mavericks', 75),
    ('83RB', 'Mavericks', 80),
    ('92XX', 'Mavericks', 95),
    ('64PC', 'Quality Strikers', 265),
    ('92yp', 'Quality Strikers', 35),
    ('9T0M', 'Quality Strikers', 75),
    ('4TFK', 'Quality Strikers', 350),
    ('8XXV', 'Quality Strikers', 85),
    ('9V5H', 'Quality Strikers', 45),
    ('CRL6', 'Quality Strikers', 50),
    ('399x', 'Quality Strikers', 35),
    ('7K6X', 'Pirates', 65),
    ('7VRC', 'Pirates', 105),
    ('54ME', 'Pirates', 225),
    ('7BWR', 'Pirates', 135),
    ('7M62', 'Pirates', 35),
    ('8B46', 'Pirates', 350),
    ('8XXP', 'Pirates', 40),
    ('4YVM', 'Pirates', 35),
    ('7J4N', 'CSK', 35),
    ('1p0t', 'CSK', 245),
    ('5YLB', 'CSK', 35),
    ('9K4V', 'CSK', 35),
    ('54TT', 'CSK', 210),
    ('Tww2', 'CSK', 160),
    ('8F4M', 'CSK', 160),
    ('PVF0', 'CSK', 85),
    ('6RMK', 'Digititans', 40),
    ('71hl', 'Digititans', 275),
    ('9BTD', 'Digititans', 40),
    ('5WR8', 'Digititans', 85),
    ('6FXM', 'Digititans', 240),
    ('7V94', 'Digititans', 45),
    ('7CFH', 'Digititans', 85),
    ('8MTK', 'Digititans', 155),
    ('5CF2', 'Digititans', 35)
),
db AS (SELECT lower(player_id) AS k, player_id, name, status, sold_to, sold_price FROM players)
-- 1. Row by row: the log vs the database
SELECT
  COALESCE(l.player_id, d.player_id)              AS player_id,
  d.name,
  l.team_name                                    AS log_team,
  d.sold_to                                      AS db_team,
  l.sold_price                                   AS log_price,
  d.sold_price                                   AS db_price,
  d.status                                       AS db_status,
  CASE
    WHEN l.player_id IS NULL AND d.status = 'Sold'   THEN 'IN DB, NOT IN LOG'
    WHEN d.k IS NULL                                 THEN 'IN LOG, NOT IN DB'
    WHEN d.status <> 'Sold'                          THEN 'NOT MARKED SOLD'
    WHEN d.sold_to IS DISTINCT FROM l.team_name      THEN 'WRONG TEAM'
    WHEN d.sold_price IS DISTINCT FROM l.sold_price  THEN 'WRONG PRICE'
    ELSE 'ok'
  END                                            AS verdict
FROM log l
FULL OUTER JOIN db d ON d.k = lower(l.player_id)
WHERE l.player_id IS NOT NULL OR d.status = 'Sold'
ORDER BY verdict <> 'ok' DESC, log_team, player_id;

-- 2. Per-team purse: log vs live
WITH expected (team_name, spend, tokens_left) AS (
  VALUES
    ('Avengers', 980, 20),
    ('Fearless Falcons', 1000, 0),
    ('Hits & Misses', 995, 5),
    ('Mavericks', 970, 30),
    ('Quality Strikers', 940, 60),
    ('Pirates', 990, 10),
    ('CSK', 965, 35),
    ('Digititans', 1000, 0)
)
SELECT
  e.team_name, e.spend AS log_spend, e.tokens_left AS log_tokens_left,
  t.tokens_left AS db_tokens_left, 1000 - t.tokens_left AS db_spend,
  (SELECT COUNT(*) FROM players p WHERE p.sold_to = e.team_name AND p.status = 'Sold') AS db_sold_count,
  CASE WHEN e.spend > 1000 THEN 'LOG OVER 1000'
       WHEN t.tokens_left = e.tokens_left THEN 'ok' ELSE 'MISMATCH' END AS verdict
FROM expected e JOIN teams t ON t.team_name = e.team_name
ORDER BY verdict <> 'ok' DESC, e.team_name;
