-- CPL 2026: apply the manual auction log to the database.
-- Generated by scripts/export_squads_config.js from data\auction_log_2026.csv.
-- Run sql/2026_verify_auction_log.sql FIRST and confirm the results.
-- Re-runnable: step 3 fully recomputes every purse.

BEGIN;

-- 0. Players added outside the auction insert (see MANUAL_PLAYERS).
INSERT INTO players (player_id, name, role, base_tokens, photo_filename, status)
VALUES ('4YVM', 'Chandra Sekhar', 'Batsman', 35, '4YVM.jpg', 'Available')
ON CONFLICT (player_id) DO NOTHING;

-- 1. Mark every logged player Sold to the right team at the logged price.
WITH log (player_id, team_name, sold_price) AS (
  VALUES
    ('7MW4', 'Avengers', 65),
    ('8HD9', 'Avengers', 205),
    ('8e5y', 'Avengers', 45),
    ('3WRK', 'Avengers', 35),
    ('5RH4', 'Avengers', 35),
    ('7J9A', 'Avengers', 350),
    ('4KQQ', 'Avengers', 190),
    ('CNC8', 'Avengers', 55),
    ('JJH6', 'Fearless Falcons', 45),
    ('3WN4', 'Fearless Falcons', 65),
    ('5L1C', 'Fearless Falcons', 55),
    ('248V', 'Fearless Falcons', 125),
    ('4x97', 'Fearless Falcons', 320),
    ('4WTI', 'Fearless Falcons', 170),
    ('8KA4', 'Fearless Falcons', 40),
    ('5DVA', 'Fearless Falcons', 100),
    ('9TXV', 'Fearless Falcons', 80),
    ('8LQL', 'Hits & Misses', 35),
    ('6JPT', 'Hits & Misses', 35),
    ('836I', 'Hits & Misses', 55),
    ('JPL9', 'Hits & Misses', 35),
    ('8J9Q', 'Hits & Misses', 260),
    ('QTC9', 'Hits & Misses', 350),
    ('81KV', 'Hits & Misses', 60),
    ('5E6D', 'Hits & Misses', 80),
    ('JKJ8', 'Hits & Misses', 85),
    ('84MR', 'Mavericks', 45),
    ('131X', 'Mavericks', 65),
    ('7ttv', 'Mavericks', 35),
    ('54RP', 'Mavericks', 295),
    ('PVH5', 'Mavericks', 70),
    ('4TDM', 'Mavericks', 210),
    ('QDK7', 'Mavericks', 75),
    ('83RB', 'Mavericks', 80),
    ('92XX', 'Mavericks', 95),
    ('64PC', 'Quality Strikers', 265),
    ('92yp', 'Quality Strikers', 35),
    ('9T0M', 'Quality Strikers', 75),
    ('4TFK', 'Quality Strikers', 350),
    ('8XXV', 'Quality Strikers', 85),
    ('9V5H', 'Quality Strikers', 45),
    ('CRL6', 'Quality Strikers', 50),
    ('399x', 'Quality Strikers', 35),
    ('7K6X', 'Pirates', 65),
    ('7VRC', 'Pirates', 105),
    ('54ME', 'Pirates', 225),
    ('7BWR', 'Pirates', 135),
    ('7M62', 'Pirates', 35),
    ('8B46', 'Pirates', 350),
    ('8XXP', 'Pirates', 40),
    ('4YVM', 'Pirates', 35),
    ('7J4N', 'CSK', 35),
    ('1p0t', 'CSK', 245),
    ('5YLB', 'CSK', 35),
    ('9K4V', 'CSK', 35),
    ('54TT', 'CSK', 210),
    ('Tww2', 'CSK', 160),
    ('8F4M', 'CSK', 160),
    ('PVF0', 'CSK', 85),
    ('6RMK', 'Digititans', 40),
    ('71hl', 'Digititans', 275),
    ('9BTD', 'Digititans', 40),
    ('5WR8', 'Digititans', 85),
    ('6FXM', 'Digititans', 240),
    ('7V94', 'Digititans', 45),
    ('7CFH', 'Digititans', 85),
    ('8MTK', 'Digititans', 155),
    ('5CF2', 'Digititans', 35)
)
UPDATE players p
SET status = 'Sold', sold_to = l.team_name, sold_price = l.sold_price
FROM log l
WHERE lower(p.player_id) = lower(l.player_id);

-- 2. Any auction player NOT in the log goes back to Available.
--    Pre-auction players (status 'PreAuction') are left untouched.
WITH log (player_id) AS (
  VALUES
    ('7MW4'),
    ('8HD9'),
    ('8e5y'),
    ('3WRK'),
    ('5RH4'),
    ('7J9A'),
    ('4KQQ'),
    ('CNC8'),
    ('JJH6'),
    ('3WN4'),
    ('5L1C'),
    ('248V'),
    ('4x97'),
    ('4WTI'),
    ('8KA4'),
    ('5DVA'),
    ('9TXV'),
    ('8LQL'),
    ('6JPT'),
    ('836I'),
    ('JPL9'),
    ('8J9Q'),
    ('QTC9'),
    ('81KV'),
    ('5E6D'),
    ('JKJ8'),
    ('84MR'),
    ('131X'),
    ('7ttv'),
    ('54RP'),
    ('PVH5'),
    ('4TDM'),
    ('QDK7'),
    ('83RB'),
    ('92XX'),
    ('64PC'),
    ('92yp'),
    ('9T0M'),
    ('4TFK'),
    ('8XXV'),
    ('9V5H'),
    ('CRL6'),
    ('399x'),
    ('7K6X'),
    ('7VRC'),
    ('54ME'),
    ('7BWR'),
    ('7M62'),
    ('8B46'),
    ('8XXP'),
    ('4YVM'),
    ('7J4N'),
    ('1p0t'),
    ('5YLB'),
    ('9K4V'),
    ('54TT'),
    ('Tww2'),
    ('8F4M'),
    ('PVF0'),
    ('6RMK'),
    ('71hl'),
    ('9BTD'),
    ('5WR8'),
    ('6FXM'),
    ('7V94'),
    ('7CFH'),
    ('8MTK'),
    ('5CF2')
)
UPDATE players p
SET status = 'Available', sold_to = NULL, sold_price = 0
WHERE p.status = 'Sold'
  AND lower(p.player_id) NOT IN (SELECT lower(player_id) FROM log);

-- 3. Rebuild every team's purse from actual spend (1000 = auction budget).
UPDATE teams t
SET tokens_left = 1000 - COALESCE((
      SELECT SUM(p.sold_price) FROM players p
      WHERE p.sold_to = t.team_name AND p.status = 'Sold'
    ), 0);

-- 4. Result before commit.
SELECT t.team_name, t.tokens_left, 1000 - t.tokens_left AS spent,
       COUNT(p.player_id) FILTER (WHERE p.status = 'Sold') AS sold_count
FROM teams t LEFT JOIN players p ON p.sold_to = t.team_name
GROUP BY t.team_name, t.tokens_left
ORDER BY t.team_name;

COMMIT;
