-- CPL 2026 pre-auction squads: 8 teams, 40 players.
-- Generated by scripts/export_preauction_sql.js from data\CPL_2026_PreAuction_Template.xlsx.
--
-- Re-runnable by design. The retained squads are fixed for the season, so this
-- UPSERTS: running it again restores status, sold_to and pre_auction_role for
-- any player a later load knocked back to Available.
--
-- Run this BEFORE the auction pool insert.

BEGIN;

INSERT INTO teams (team_id, team_name, logo_file, tokens_left, max_tokens, max_squad_size) VALUES
  ('CPL_T01', 'Avengers', 'Avengers.png', 1000, 1000, 14),
  ('CPL_T02', 'Fearless Falcons', 'Feralessfalcons.png', 1000, 1000, 14),
  ('CPL_T03', 'Hits & Misses', 'HitsMisses.png', 1000, 1000, 14),
  ('CPL_T04', 'Mavericks', 'Mavericks.png', 1000, 1000, 14),
  ('CPL_T05', 'Quality Strikers', 'quality_strikers.png', 1000, 1000, 14),
  ('CPL_T06', 'Pirates', 'Pirates.png', 1000, 1000, 14),
  ('CPL_T07', 'CSK', 'csk.png', 1000, 1000, 14),
  ('CPL_T08', 'Digititans', 'digititans.png', 1000, 1000, 14)
ON CONFLICT (team_id) DO UPDATE SET
  team_name = EXCLUDED.team_name,
  logo_file = EXCLUDED.logo_file;

-- Clear existing pre-auction markers before re-asserting them below. Without
-- this, a captain or vice-captain change between loads collides with the
-- one_captain_per_team / one_vc_per_team unique indexes: the new captain's row
-- is upserted while the previous captain still carries pre_auction_role =
-- 'Captain' for the same team. Safe on a fresh database (matches no rows).
UPDATE players
SET pre_auction_role = NULL, is_captain = FALSE, is_vice_captain = FALSE
WHERE pre_auction_role IS NOT NULL
   OR player_id IN ('5DXX', '7EK2', '8E25', '2BJB', 'LTI7', '6NN4', '2X2H', 'DPN8', 'XWX1', '91RY', '7B8V', '6RHV', 'XXK4', '7N91', '67HW', '4LQC', '43EB', 'CQX4', 'MXL5', 'MPB8', '615R', '44QM', '68EY', '5F0W', 'QHE1', '628B', '6RMT', '54YB', '930P', '6LJX', '304A', '14HB', 'CNC0', '4V2H', '8E1D', '5CLA', '917V', '7R2W', '61EX', '8Q1H');

INSERT INTO players (
  player_id, name, role, base_tokens, photo_filename, department,
  pre_auction_role, sold_to, is_captain, is_vice_captain, availability,
  status, sold_price
) VALUES
  ('5DXX', 'Siva Naga Kishore Raju Samanthapudi', 'All-rounder', 0, '5DXX.jpg', 'All-rounder', 'Captain', 'Avengers', true, false, 'Unknown', 'PreAuction', 0),
  ('7EK2', 'Kalyan Bollapragada SS', 'All-rounder', 0, '7EK2.jpg', 'All-rounder', 'ViceCaptain', 'Avengers', false, true, 'Unknown', 'PreAuction', 0),
  ('8E25', 'Mallikarjun Maram', 'All-rounder', 0, '8E25.jpg', 'All-rounder', 'Squad', 'Avengers', false, false, 'Unknown', 'PreAuction', 0),
  ('2BJB', 'Pradeep Kumar Pala', 'All-rounder', 0, '2BJB.jpg', 'All-rounder', 'Squad', 'Avengers', false, false, 'Unknown', 'PreAuction', 0),
  ('LTI7', 'Pavan Pulasani', 'All-rounder', 0, 'LTI7.jpg', 'All-rounder', 'Squad', 'Avengers', false, false, 'Unknown', 'PreAuction', 0),
  ('6NN4', 'Rajasekhara Reddy Gowkanapalli', 'All-rounder', 0, '6NN4.jpg', 'All-rounder', 'Captain', 'Fearless Falcons', true, false, 'Unknown', 'PreAuction', 0),
  ('2X2H', 'Chandra Sekhar Gubbala', 'All-rounder', 0, '2X2H.jpg', 'All-rounder', 'ViceCaptain', 'Fearless Falcons', false, true, 'Unknown', 'PreAuction', 0),
  ('DPN8', 'Aravinda Pai', 'All-rounder', 0, 'DPN8.jpg', 'All-rounder', 'Squad', 'Fearless Falcons', false, false, 'Unknown', 'PreAuction', 0),
  ('XWX1', 'Amit Bhattacharjee', 'All-rounder', 0, 'XWX1.jpg', 'All-rounder', 'Squad', 'Fearless Falcons', false, false, 'Unknown', 'PreAuction', 0),
  ('91RY', 'Omkar Shreeshail Baradol', 'All-rounder', 0, '91RY.jpg', 'All-rounder', 'Squad', 'Fearless Falcons', false, false, 'Unknown', 'PreAuction', 0),
  ('7B8V', 'Saravanan Krishnamoorthy', 'All-rounder', 0, '7B8V.jpg', 'All-rounder', 'Captain', 'Hits & Misses', true, false, 'Unknown', 'PreAuction', 0),
  ('6RHV', 'Fasiuddin Mohammad', 'All-rounder', 0, '6RHV.jpg', 'All-rounder', 'ViceCaptain', 'Hits & Misses', false, true, 'Unknown', 'PreAuction', 0),
  ('XXK4', 'Ramu Pedada', 'Batsman', 0, 'XXK4.jpg', 'Batting', 'Squad', 'Hits & Misses', false, false, 'Unknown', 'PreAuction', 0),
  ('7N91', 'Prasad Renikunta', 'All-rounder', 0, '7N91.jpg', 'All-rounder', 'Squad', 'Hits & Misses', false, false, 'Unknown', 'PreAuction', 0),
  ('67HW', 'Bhavani Reddy Veduru', 'All-rounder', 0, '67HW.jpg', 'All-rounder', 'Squad', 'Hits & Misses', false, false, 'Unknown', 'PreAuction', 0),
  ('4LQC', 'Pranay Barigela', 'All-rounder', 0, '4LQC.jpg', 'All-rounder', 'Captain', 'Mavericks', true, false, 'Unknown', 'PreAuction', 0),
  ('43EB', 'Sai Bhuvaneshwar Valmiki', 'WicketKeeper', 0, '43EB.jpg', 'Wicket Keeping', 'ViceCaptain', 'Mavericks', false, true, 'Unknown', 'PreAuction', 0),
  ('CQX4', 'Prakash Kilaparti', 'All-rounder', 0, 'CQX4.jpg', 'All-rounder', 'Squad', 'Mavericks', false, false, 'Unknown', 'PreAuction', 0),
  ('MXL5', 'Anil Maradani', 'Batsman', 0, 'MXL5.jpg', 'Batting', 'Squad', 'Mavericks', false, false, 'Unknown', 'PreAuction', 0),
  ('MPB8', 'Sriharsha Siddam', 'Batsman', 0, NULL, NULL, 'Squad', 'Mavericks', false, false, 'Unknown', 'PreAuction', 0),
  ('615R', 'Siva Teja Pidikiti', 'All-rounder', 0, '615R.jpg', 'All-rounder', 'Captain', 'Quality Strikers', true, false, 'Unknown', 'PreAuction', 0),
  ('44QM', 'Niranjan Reddy Midde', 'All-rounder', 0, '44QM.jpg', 'All-rounder', 'ViceCaptain', 'Quality Strikers', false, true, 'Unknown', 'PreAuction', 0),
  ('68EY', 'Harshavardhan Reddy Yakkanti', 'All-rounder', 0, '68EY.jpg', 'All-rounder', 'Squad', 'Quality Strikers', false, false, 'Unknown', 'PreAuction', 0),
  ('5F0W', 'Rahul Voruganti', 'All-rounder', 0, '5F0W.jpg', 'All-rounder', 'Squad', 'Quality Strikers', false, false, 'Unknown', 'PreAuction', 0),
  ('QHE1', 'Praveen Mattaparthi', 'WicketKeeper', 0, 'QHE1.jpg', 'Wicket Keeping', 'Squad', 'Quality Strikers', false, false, 'Unknown', 'PreAuction', 0),
  ('628B', 'Jagadish Koppula', 'All-rounder', 0, '628B.jpg', 'All-rounder', 'Captain', 'Pirates', true, false, 'Unknown', 'PreAuction', 0),
  ('6RMT', 'Veera Venkata Naga Satya Raj Gollapalli', 'All-rounder', 0, '6RMT.jpg', 'All-rounder', 'ViceCaptain', 'Pirates', false, true, 'Unknown', 'PreAuction', 0),
  ('54YB', 'Adithya Varma Penmetcha', 'All-rounder', 0, '54YB.jpg', 'All-rounder', 'Squad', 'Pirates', false, false, 'Unknown', 'PreAuction', 0),
  ('930P', 'Rithikesh Mamidi', 'All-rounder', 0, NULL, 'All-rounder', 'Squad', 'Pirates', false, false, 'Unknown', 'PreAuction', 0),
  ('6LJX', 'Mohammad Aquib Noman', 'Batsman', 0, NULL, NULL, 'Squad', 'Pirates', false, false, 'Unknown', 'PreAuction', 0),
  ('304A', 'Shubham Kumar Jena', 'All-rounder', 0, '304A.jpg', 'All-rounder', 'Captain', 'CSK', true, false, 'Unknown', 'PreAuction', 0),
  ('14HB', 'Mahether Reddy Bhavanam', 'Bowler', 0, '14HB.jpg', 'Bowler', 'ViceCaptain', 'CSK', false, true, 'Unknown', 'PreAuction', 0),
  ('CNC0', 'Venkata Ramana Sashidhar Vasamsetty', 'All-rounder', 0, NULL, NULL, 'Squad', 'CSK', false, false, 'Unknown', 'PreAuction', 0),
  ('4V2H', 'Debargha Gupta', 'All-rounder', 0, '4V2H.jpg', 'All-rounder', 'Squad', 'CSK', false, false, 'Unknown', 'PreAuction', 0),
  ('8E1D', 'Mahesh Gaada', 'WicketKeeper', 0, '8E1D.jpg', 'Wicket Keeping', 'Squad', 'CSK', false, false, 'Unknown', 'PreAuction', 0),
  ('5CLA', 'Gopi Krishna Kanth Dabbakuti', 'All-rounder', 0, '5CLA.jpg', 'All-rounder', 'Captain', 'Digititans', true, false, 'Unknown', 'PreAuction', 0),
  ('917V', 'Bharath Chaitanya Jagana', 'All-rounder', 0, '917V.jpg', 'All-rounder', 'ViceCaptain', 'Digititans', false, true, 'Unknown', 'PreAuction', 0),
  ('7R2W', 'Rajwinder Singh', 'All-rounder', 0, '7R2W.jpg', 'All-rounder', 'Squad', 'Digititans', false, false, 'Unknown', 'PreAuction', 0),
  ('61EX', 'Jyothi Radithya Koredla', 'All-rounder', 0, '61EX.jpg', 'All-rounder', 'Squad', 'Digititans', false, false, 'Unknown', 'PreAuction', 0),
  ('8Q1H', 'Pavan Kumar Gavara', 'All-rounder', 0, '8Q1H.jpg', 'All-rounder', 'Squad', 'Digititans', false, false, 'Unknown', 'PreAuction', 0)
ON CONFLICT (player_id) DO UPDATE SET
  name             = EXCLUDED.name,
  role             = EXCLUDED.role,
  photo_filename   = EXCLUDED.photo_filename,
  pre_auction_role = EXCLUDED.pre_auction_role,
  sold_to          = EXCLUDED.sold_to,
  is_captain       = EXCLUDED.is_captain,
  is_vice_captain  = EXCLUDED.is_vice_captain,
  status           = 'PreAuction',
  sold_price       = 0;

COMMIT;
