-- =====================================================
-- CPL 2025 Data Insertion Script
-- Handles existing data and inserts new player data
-- =====================================================

-- Step 1: Backup existing data (OPTIONAL - run if you want to keep old data)
-- =====================================================
/*
CREATE TABLE IF NOT EXISTS players_backup AS SELECT * FROM players;
CREATE TABLE IF NOT EXISTS teams_backup AS SELECT * FROM teams;
CREATE TABLE IF NOT EXISTS auction_history_backup AS SELECT * FROM auction_history;
*/

-- Step 2: Clear existing data
-- =====================================================
-- Clear in correct order due to foreign key constraints

DELETE FROM auction_history;
-- Cleared auction history

DELETE FROM players;
-- Cleared all players

-- Optional: Clear teams if you want fresh team data
-- DELETE FROM teams;

-- Step 3: Reset sequences for clean IDs
-- =====================================================
ALTER SEQUENCE players_id_seq RESTART WITH 1;
ALTER SEQUENCE auction_history_id_seq RESTART WITH 1;
-- Optional: ALTER SEQUENCE teams_id_seq RESTART WITH 1;

-- Step 4: Verify cleanup
-- =====================================================
SELECT 
  'players' as table_name, 
  COUNT(*) as remaining_records 
FROM players
UNION ALL
SELECT 
  'teams' as table_name, 
  COUNT(*) as remaining_records 
FROM teams
UNION ALL
SELECT 
  'auction_history' as table_name, 
  COUNT(*) as remaining_records 
FROM auction_history;

-- Expected: players=0, auction_history=0
-- teams may have records if not cleared

-- =====================================================
-- Step 5: Insert CPL 2025 Teams (if needed)
-- =====================================================
-- Uncomment and customize if you need to insert teams

/*
INSERT INTO teams (team_id, team_name, logo_file, tokens_left, max_tokens, max_squad_size, batsman_budget, bowler_budget, allrounder_budget, wicketkeeper_budget) VALUES
('CPL_T01', 'Team Alpha', 'team1_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T02', 'Team Beta', 'team2_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T03', 'Team Gamma', 'team3_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T04', 'Team Delta', 'team4_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T05', 'Team Epsilon', 'team5_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T06', 'Team Zeta', 'team6_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T07', 'Team Eta', 'team7_logo.png', 1200, 1200, 15, 420, 420, 240, 120),
('CPL_T08', 'Team Theta', 'team8_logo.png', 1200, 1200, 15, 420, 420, 240, 120);
*/

-- =====================================================
-- Step 6: Insert CPL 2025 Players (94 players for auction)
-- =====================================================
-- This will be generated by running: python process_cpl_registrations.py
-- The generated SQL will be in: cpl_auction_2025_insert.sql
-- Copy and paste that content here, or run it separately

-- Placeholder - replace with actual generated SQL
-- INSERT INTO players (player_id, name, role, department, base_tokens, photo_filename, status, auction_order) VALUES
-- ... (generated content from process_cpl_registrations.py)

-- =====================================================
-- Step 7: Verify insertion
-- =====================================================

-- Check total player count
SELECT COUNT(*) as total_players FROM players;
-- Expected: 94 players

-- Check role distribution
SELECT 
  role,
  COUNT(*) as player_count,
  MIN(base_tokens) as min_tokens,
  MAX(base_tokens) as max_tokens,
  ROUND(AVG(base_tokens), 1) as avg_tokens
FROM players 
GROUP BY role 
ORDER BY role;

-- Expected distribution:
-- All-rounder: 42 players
-- Batsman: 34 players
-- WicketKeeper: 14 players
-- Bowler: 4 players

-- Check auction order
SELECT 
  role,
  MIN(auction_order) as first_order,
  MAX(auction_order) as last_order,
  COUNT(*) as count
FROM players
GROUP BY role
ORDER BY MIN(auction_order);

-- Expected order: Batsman (1000s), Bowler (2000s), All-rounder (3000s), WicketKeeper (4000s)

-- Check for any data issues
SELECT 
  'Duplicate Player IDs' as check_type,
  COUNT(*) as issue_count
FROM (
  SELECT player_id 
  FROM players 
  GROUP BY player_id 
  HAVING COUNT(*) > 1
) duplicates
UNION ALL
SELECT 
  'Invalid Roles' as check_type,
  COUNT(*) as issue_count
FROM players 
WHERE role NOT IN ('Batsman', 'Bowler', 'All-rounder', 'WicketKeeper')
UNION ALL
SELECT 
  'Invalid Status' as check_type,
  COUNT(*) as issue_count
FROM players 
WHERE status NOT IN ('Available', 'Sold', 'Unsold')
UNION ALL
SELECT 
  'Missing Auction Order' as check_type,
  COUNT(*) as issue_count
FROM players 
WHERE auction_order IS NULL;

-- All counts should be 0

-- =====================================================
-- Step 8: Preview first few players by auction order
-- =====================================================
SELECT 
  auction_order,
  player_id,
  name,
  role,
  base_tokens,
  status
FROM players
ORDER BY auction_order
LIMIT 10;

-- =====================================================
-- NOTES FOR CAPTAIN ASSIGNMENT:
-- =====================================================
-- 
-- The 23 captains from the CAPTAINS tab should be assigned
-- to teams BEFORE the auction starts. Use this template:
--
-- UPDATE players 
-- SET status = 'Sold', 
--     sold_to = 'CPL_T01',  -- Team ID
--     sold_price = 0        -- Captains are pre-assigned
-- WHERE player_id = 'CAPTAIN_PLAYER_ID';
--
-- Repeat for all 23 captains, assigning 2-3 per team
-- =====================================================

-- =====================================================
-- READY FOR AUCTION!
-- =====================================================
-- After running this script:
-- 1. Verify all checks pass (no issues found)
-- 2. Assign captains to teams using UPDATE statements
-- 3. Load data in your auction app
-- 4. Start the auction!
-- =====================================================